language: objective-c
osx_image: xcode8.2
cache:
- bundler
before_install:
- bundle install --without=documentation
- brew update && brew install swiftlint
script:
- fastlane test
- bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash)
