language: objective-c
osx_image: xcode8.2
cache:
  - bundler
  - cocoapods
before_install:
  - pod repo update --silent
script:
  - bundle exec fastlane test
  - bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash)
