language: objective-c
osx_image: xcode8.1
cache:
- bundler
before_install:
- bundle install --without=documentation
script:
- fastlane test
- bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash)
